#!/bin/bash
#
export DEBIAN_FRONTEND=noninteractive

APT_ARGS='-q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'

apt ${APT_ARGS} update
apt ${APT_ARGS} upgrade

# Insert any instructions for your Raspberry Pi setup here

# Comment out this line if you want the Rapsberry Pi image to continue running after installation is complete

shutdown -h now
